language: swift
osx_image: xcode9.2
env:
  matrix:
    - COMMAND="test-ios"
    - COMMAND="test-macos"
    - COMMAND="test-tvos"
    - COMMAND="test-watchos"
    - COMMAND="test-native"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - swift -version
  - sh build.sh "$COMMAND"
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'MiniDOM'
